<?php

/**
 * The template for displaying all single posts
 *
 * @package Fatties_Corporation
 */
get_header();

?>

<div class="single-post-page">
  <div class="blog-container single-layout">
    
    <main class="single-main">
      <?php
      while (have_posts()):
        the_post();

        // Get categories
        $categories = get_the_category();
        $first_category = !empty($categories) ? $categories[0] : null;
        ?>

        <div class="single-header">
           <div class="breadcrumb">
            <a href="<?php echo home_url('/'); ?>">Trang chủ</a> / 
            <a href="<?php echo home_url('/blog'); ?>">Blog</a> / 
            <?php if ($first_category): ?>
              <a class="current" href="<?php echo get_category_link($first_category->term_id); ?>"><?php echo esc_html($first_category->name); ?></a>
            <?php endif; ?>
          </div>

          <h1 class="single-title"><?php the_title(); ?></h1>

          <div class="single-meta">
            <span class="meta-item">
               <ion-icon name="person-outline"></ion-icon>
               <?php the_author(); ?>
            </span>
            <span class="meta-item">
               <ion-icon name="calendar-outline"></ion-icon>
               <?php echo get_the_date('d/m/Y'); ?>
            </span>
             <span class="meta-item">
               <ion-icon name="time-outline"></ion-icon>
               <?php echo fatties_corp_reading_time(); ?> phút đọc
            </span>
          </div>
        </div>

        <?php if (has_post_thumbnail()): ?>
          <div class="single-thumbnail">
            <?php the_post_thumbnail('full'); ?>
          </div>
        <?php endif; ?>

        <div class="single-content">
          <?php the_content(); ?>
        </div>

        <div class="single-footer">
           <div class="post-tags">
             <?php
        $tags = get_the_tags();
        if ($tags) {
          foreach ($tags as $tag) {
            echo '<a href="' . get_tag_link($tag->term_id) . '" class="tag-link">#' . $tag->name . '</a>';
          }
        }
        ?>
           </div>
           
           <div class="share-buttons">
             <span>Chia sẻ:</span>
             <a href="https://www.facebook.com/sharer/sharer.php?u=<?php the_permalink(); ?>" target="_blank" class="share-btn fb"><ion-icon name="logo-facebook"></ion-icon></a>
             <a href="https://twitter.com/intent/tweet?url=<?php the_permalink(); ?>&text=<?php the_title(); ?>" target="_blank" class="share-btn tw"><ion-icon name="logo-twitter"></ion-icon></a>
             <a href="https://www.linkedin.com/shareArticle?mini=true&url=<?php the_permalink(); ?>" target="_blank" class="share-btn li"><ion-icon name="logo-linkedin"></ion-icon></a>
           </div>

        </div>

        <div class="single-comments">
          <?php
          if (comments_open() || get_comments_number()):
            comments_template();
          endif;
          ?>
        </div>

      <?php endwhile; // End of the loop. ?>
    </main>

    <aside class="single-sidebar">
      <div class="sidebar-inner-sticky">
        <div class="sidebar-widget sidebar-cta-widget">
          <h3 class="widget-title">Bạn muốn khởi động dự án?</h3>
          <p class="sidebar-cta-desc">
            Đội ngũ của chúng tôi sẵn sàng hiện thực hóa ý tưởng của bạn. Hãy liên hệ ngay để thảo luận về lộ trình!
          </p>
          <a href="<?php echo home_url('/contact'); ?>" class="sidebar-cta-btn">
            Liên hệ ngay
          </a>
        </div>

        <div class="sidebar-widget toc-widget">
          <h3 class="widget-title">Mục lục</h3>
          <div id="toc-container">
             <!-- TOC will be generated by JS -->
          </div>
        </div>
        
         <div class="sidebar-widget latest-posts-widget">
          <h3 class="widget-title">Bài viết mới nhất</h3>
          <?php
          $latest_posts = new WP_Query(array(
            'posts_per_page' => 5,
            'post_status' => 'publish',
            'post__not_in' => array(get_the_ID()),
          ));

          if ($latest_posts->have_posts()):
            while ($latest_posts->have_posts()):
              $latest_posts->the_post();
              ?>
                <div class="widget-post-item">
                   <a href="<?php the_permalink(); ?>" class="widget-post-link">
                     <?php if (has_post_thumbnail()): ?>
                        <div class="widget-post-thumb" style="background-image: url('<?php the_post_thumbnail_url('thumbnail'); ?>');"></div>
                     <?php endif; ?>
                     <div class="widget-post-info">
                        <h4 class="widget-post-title"><?php the_title(); ?></h4>
                        <div class="widget-post-date"><?php echo get_the_date('d/m/Y'); ?></div>
                     </div>
                   </a>
                </div>
              <?php
            endwhile;
            wp_reset_postdata();
          endif;
          ?>
        </div>
      </div>
    </aside>

  </div>

  <!-- Related Posts -->
  <?php
  $orig_post = $post;
  global $post;
  $cats = get_the_category($post->ID);

  if ($cats) {
    $cat_ids = array();
    foreach ($cats as $individual_cat) {
      $cat_ids[] = $individual_cat->term_id;
    }

    $args = array(
      'category__in' => $cat_ids,
      'post__not_in' => array($post->ID),
      'posts_per_page' => 3,
      'ignore_sticky_posts' => 1,  // Replaces deprecated caller_get_posts
      'orderby' => 'rand'  // Optional: Randomize related posts
    );

    $my_query = new WP_Query($args);

    if ($my_query->have_posts()):
      ?>
        <section class="related-section">
          <div class="blog-container">
            <h2 class="section-title">Bài viết liên quan</h2>
            <div class="related-grid">
              <?php
              while ($my_query->have_posts()):
                $my_query->the_post();
                $thumb = get_the_post_thumbnail_url(get_the_ID(), 'medium');
                ?>
                  <div class="related-card">
                     <a href="<?php the_permalink(); ?>" class="related-thumb" style="background-image: url('<?php echo esc_url($thumb ? $thumb : get_template_directory_uri() . '/assets/images/default-blog.jpg'); ?>');"></a>
                     <div class="related-body">
                       <div class="related-meta">
                         <ion-icon name="calendar-outline" style="vertical-align: middle; margin-right: 5px;"></ion-icon>
                         <?php echo get_the_date('d/m/Y'); ?>
                       </div>
                       <h3><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h3>
                     </div>
                  </div>
              <?php
              endwhile;
              ?>
            </div>
          </div>
        </section>
      <?php
    endif;
  }

  $post = $orig_post;
  wp_reset_postdata();
  ?>
</div>
<script>
document.addEventListener('DOMContentLoaded', function() {
    const content = document.querySelector('.single-content');
    const tocContainer = document.getElementById('toc-container');
    
    if (content && tocContainer) {
        const headings = content.querySelectorAll('h2, h3, h4');
        
        if (headings.length > 0) {
            const ul = document.createElement('ul');
            const tocLinks = [];

            headings.forEach((heading, index) => {
                const id = 'heading-' + index;
                heading.setAttribute('id', id);
                
                const li = document.createElement('li');
                li.className = 'toc-' + heading.tagName.toLowerCase();
                
                const a = document.createElement('a');
                a.href = '#' + id;
                a.textContent = heading.textContent;
                a.dataset.target = id;
                
                a.addEventListener('click', (e) => {
                    e.preventDefault();
                    document.getElementById(id).scrollIntoView({ behavior: 'smooth' });
                });

                li.appendChild(a);
                ul.appendChild(li);
                tocLinks.push(a);
            });
            tocContainer.appendChild(ul);

            // HIGHLIGHT ON SCROLL
            const observerOptions = {
                root: null,
                rootMargin: '-100px 0px -60% 0px', // Adjust active zone
                threshold: 0
            };

            const observer = new IntersectionObserver((entries) => {
                entries.forEach(entry => {
                    if (entry.isIntersecting) {
                        const id = entry.target.getAttribute('id');
                        
                        // Remove active class from all
                        tocLinks.forEach(link => link.classList.remove('active'));

                        // Add active class to current
                        const currentLink = tocLinks.find(link => link.dataset.target === id);
                        if (currentLink) {
                            currentLink.classList.add('active');
                        }
                    }
                });
            }, observerOptions);

            headings.forEach(heading => {
                observer.observe(heading);
            });
        } else {
             tocContainer.innerHTML = '<p class="no-toc">Không có mục lục</p>';
        }
    }
});
</script>

<?php get_footer(); ?>
